apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  prometheus-additional.yaml: |
    - job_name: 'ethereum-execution'
      scrape_interval: 15s
      metrics_path: /debug/metrics/prometheus
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - ethereum
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: geth-testnet
          action: keep
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: metrics
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
          action: replace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
          action: replace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
          action: replace
