apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  ports:
  - port: {{ .Values.nginx.ports.http }}
    name: http
  clusterIP: None
  selector:
    app: {{ .Values.nginx.name }}
